version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  nekotaku:
    build: ./firebase
    environment:
      - NODE_ENV=development
    depends_on:      
      - mongo    # 依存するコンテナを書く
    volumes:
      - ../public:/app/public
      - ../data:/app/data
      - ../config:/app/config
      - ../scripts:/app/scripts
      - ../src:/app/src
      - ../tests:/app/tests
      - ../.firebaserc:/app/.firebaserc
      - ../firebase.json:/app/firebase.json
      - ../.flowconfig:/app/.flowconfig
      - ../tsconfig.json:/app/tsconfig.json
      - ../postcss.config.js:/app/postcss.config.js
      - ../.eslintrc.js:/app/.eslintrc.js
      - ../firebase/database.rules.json:/app/firebase/database.rules.json
      - ../index.js:/app/index.js
      - ../babel.config.js:/app/babel.config.js
      - ../CHANGELOG.md:/app/CHANGELOG.md
      - ../dist/lib:/app/lib
      - ../vue.config.js:/app/vue.config.js
      - ../cypress.json:/app/cypress.json
      - ../dist/tmp:/app/tmp
    ports:
      - 8080:8080
    command: [npm, run, serve]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example