version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  nekotaku:
    build: ./firebase
    environment:
      - NODE_ENV=production
    depends_on:      
      - mongo    # 依存するコンテナを書く
    volumes:
      - ../public:/app/public
      - ../data:/app/data
      - ../config:/app/config
      - ../scripts:/app/scripts
      - ../src:/app/src
      - ../.firebaserc:/app/.firebaserc
      - ../firebase.json:/app/firebase.json
      - ../.flowconfig:/app/.flowconfig
      - ../.postcssrc.yml:/app/.postcssrc.yml
      - ../.eslintrc.yml:/app/.eslintrc.yml
      - ../database.rules.json:/app/database.rules.json
      - ../index.js:/app/index.js
      - ../webpack.config.babel.js:/app/webpack.config.babel.js
      - ../.babelrc:/app/.babelrc
      - ../CHANGELOG.md:/app/CHANGELOG.md
      - ../dist/lib:/app/lib
    ports:
      - 8080:8080
    # command: [yarn, start, --host, "0.0.0.0", --port, "8080"]
    command: [node, index.js]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example