version: '3'
services:
  nekotaku:
    build: ./firebase
    environment:
      - NODE_ENV=development
    volumes:
      - ../public:/app/public
      - ../data:/app/data
      - ../config:/app/config
      - ../scripts:/app/scripts
      - ../src:/app/src
      - ../tests:/app/tests
      - ../.firebaserc:/app/.firebaserc
      - ../firebase.json:/app/firebase.json
      - ../.flowconfig:/app/.flowconfig
      - ../tsconfig.json:/app/tsconfig.json
      - ../postcss.config.js:/app/postcss.config.js
      - ../.eslintrc.js:/app/.eslintrc.js
      - ../firebase/database.rules.json:/app/firebase/database.rules.json
      - ../index.js:/app/index.js
      - ../babel.config.js:/app/babel.config.js
      - ../CHANGELOG.md:/app/CHANGELOG.md
      - ../dist/lib:/app/lib
      - ../vue.config.js:/app/vue.config.js
      - ../cypress.json:/app/cypress.json
      - ../dist/tmp:/app/tmp
      - ../package.json:/app/package.json
    ports:
      - 8080:8080
    command: [npm, run, serve]
